package xyz.tironi.zoen.ui

// Generated by scripts/export-android-pet.py from the original Swift sprite.
internal object OriginalPetArt {
    const val width = 26
    const val height = 22
    const val sourceSha256 = "acbbe17cb17d0c81f0aebcf939957e441299b3dde8a89b03bb138bf72174876c"
    private val side = listOf(
        "................OO.OO.....",
        "...............OPO.OPO....",
        "...............OPO.OPO....",
        "...............OPOOOPO....",
        "..............OMGGGGGGO...",
        ".............OMMGGGGGGGO..",
        ".............OMGGGEEGGGGO.",
        "............OMMGGGEHGGGGO.",
        "............OMGGGGGGGGWWWO",
        "...........OMMGGGGGGWWWWWO",
        "...........OMGGGGGGWWWNWWO",
        "..OOOOOOOOOMMGGGGGGOWWWWO.",
        ".OGGGGGGGGGGGGGGGGGGOOOO..",
        "OGGGGGGGGGGGGGGGGGGGO.....",
        "OGGGGGGGGGGGGGGGGGGGO.....",
        "TOGGGGGGGGGGGGGGGGGGO.....",
        "T.OGGWWWWWWWWWWWGGGO......",
        "T..OGGGGGGGGGGGGGGO.......",
    )
    private val legs = listOf(
        "...OGO..OGO....OGO..OGO...",
        "...OGO..OGO....OGO..OGO...",
        "...OGO..OGO....OGO..OGO...",
        "...OKO..OKO....OKO..OKO...",
    )
    val front = side + legs
    val sleeping = listOf(".".repeat(width), ".".repeat(width), ".".repeat(width)) + eyesClosed(side) + "...OOOO.........OOOO......"
    val blinking = eyesClosed(front)
    val palette = mapOf(
        'O' to 0xFF3A3340L,
        'G' to 0xFF9C97A3L,
        'M' to 0xFF4B4452L,
        'P' to 0xFFF4A3A8L,
        'W' to 0xFFF3EEE8L,
        'E' to 0xFF17131CL,
        'H' to 0xFFFFFFFFL,
        'N' to 0xFF6E6673L,
        'K' to 0xFF2C2730L,
        'T' to 0xFF4B4452L,
    )
    private fun eyesClosed(rows: List<String>) = rows.mapIndexed { y, row ->
        when (y) { 6 -> row.replace('E', 'G'); 7 -> row.replace('E', 'O').replace('H', 'O'); else -> row }
    }
}
