#!/usr/bin/env python3
"""Export the original Swift pet pixels and palette for native Android rendering."""
import hashlib
import argparse
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Verify generated pixels without rewriting them')
args = parser.parse_args()
source = root / 'apple/Shared/Apps/Native/PetViews.swift'
text = source.read_text().split('struct PetSprite:', 1)[0]
def rows(name):
    match = re.search(r'static let ' + name + r'(?:\s*:\s*\[String\])?\s*=\s*\[(.*?)\]', text, re.S)
    if not match:
        raise ValueError('Original sprite rows not found: ' + name)
    return re.findall(r'"([^"\n]+)"', match[1])
side = rows('sideRows'); legs = rows('legsA')
palette = dict(re.findall(r'"(.)": Color\(hex: "#([0-9A-Fa-f]{6})"\)', text))
assert len(side) == 18 and len(legs) == 4 and len(palette) == 10
assert set(''.join(side + legs)) <= palette.keys() | {'.'}
lines = ['package xyz.tironi.zoen.ui', '', '// Generated by scripts/export-android-pet.py from the original Swift sprite.',
    'internal object OriginalPetArt {', '    const val width = 26', '    const val height = 22',
    '    const val sourceSha256 = "' + hashlib.sha256(source.read_bytes()).hexdigest() + '"',
    '    private val side = listOf(']
lines += ['        "' + row + '",' for row in side]
lines += ['    )', '    private val legs = listOf(']
lines += ['        "' + row + '",' for row in legs]
lines += ['    )', '    val front = side + legs', '    val sleeping = listOf(".".repeat(width), ".".repeat(width), ".".repeat(width)) + eyesClosed(side) + "...OOOO.........OOOO......"',
    '    val blinking = eyesClosed(front)', '    val palette = mapOf(']
lines += ["        '" + key + "' to 0xFF" + value.upper() + 'L,' for key, value in palette.items()]
lines += ['    )', '    private fun eyesClosed(rows: List<String>) = rows.mapIndexed { y, row ->',
    '        when (y) { 6 -> row.replace(\'E\', \'G\'); 7 -> row.replace(\'E\', \'O\').replace(\'H\', \'O\'); else -> row }', '    }', '}', '']
target = root / 'android/app/src/main/java/xyz/tironi/zoen/ui/GeneratedPetArt.kt'
generated = '\n'.join(lines)
if args.check:
    if not target.is_file() or target.read_text() != generated:
        raise SystemExit('Original pet pixels changed; run scripts/export-android-pet.py and review the native rendering')
else:
    target.write_text(generated)
print(str(target.relative_to(root)))
