#!/usr/bin/env python3
"""Export the original ink icon control points and motion beats as Kotlin data."""
import hashlib
import gzip
import json
from pathlib import Path
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
icons = root / "apple/Shared/DesignSystem/ZoenInkIcons.swift"
glyphs = root / "apple/Shared/DesignSystem/ZoenIcons.swift"
s = icons.read_text()
g = glyphs.read_text()
enum = g[g.index("enum ZoenGlyph:"):g.index("/// One glyph")]
seed = """
extension ZoenGlyph {
    var seed: UInt64 { UInt64(abs(rawValue.hashValueStable)) }
}
private extension String {
    var hashValueStable: Int { unicodeScalars.reduce(5381) { ($0 &* 33) &+ Int($1.value) } }
}
"""
art = s[s.index("enum IconDirection:"):s.index("// MARK: Rendering")]
motion = s[s.index("struct IconMotion {"):s.index("/// The ink icon view:")]
hand = root / "apple/Shared/DesignSystem/HandDrawn.swift"
hand_source = hand.read_text()
rng = hand_source[hand_source.index("struct InkRNG {"):hand_source.index("enum InkPalette {")]
geometry = "enum Ink {\n" + hand_source[hand_source.index("    static func catmull("):hand_source.index("/// `-RodaFreezeArt")]
shape = s[s.index("enum IconLayer {"):s.index("/// The selected state:")].replace("struct InkIconShape: Shape", "struct InkIconShape")
path_support = """
struct Path {
    var polygons: [[CGPoint]] = []
    var pending: [CGPoint] = []
    mutating func addLines(_ points: [CGPoint]) { pending += points }
    mutating func closeSubpath() { polygons.append(pending); pending = [] }
    mutating func addPath(_ path: Path) { polygons += path.polygons }
}
"""
export = r"""
func point(_ p: CGPoint) -> [Double] { [Double(p.x), Double(p.y)] }
func mark(_ m: InkMark) -> [String: Any] {
    ["points": m.points.map(point), "closed": m.closed, "smooth": m.smooth,
     "weight": Double(m.weight), "overshoot": m.overshoot]
}
func beat(_ m: IconMotion) -> [Double] {
    [Double(m.accentX), Double(m.accentY), m.accentRot, Double(m.accentScale), m.accentOpacity, m.rot, Double(m.scale)]
}
let data = ZoenGlyph.allCases.map { glyph -> [String: Any] in
    let a = glyph.doodleArt!
    return ["name": glyph.rawValue, "seed": glyph.seed, "base": a.base.map(mark), "accent": a.accent.map(mark),
        "blots": a.blots.map { [Double($0.0.x), Double($0.0.y), Double($0.1)] },
        "accentBlots": a.accentBlots.map { [Double($0.0.x), Double($0.0.y), Double($0.1)] },
        "wash": a.wash.map(mark), "pivot": point(a.pivot), "beats": glyph.motionBeats.map(beat),
        "paths": [IconLayer.base, .accent, .wash].map { layer in
            InkIconShape(glyph: glyph, direction: .doodle, layer: layer).path(in: CGRect(x: 0, y: 0, width: 24, height: 24)).polygons.map { $0.map(point) }
        },
        "animatedPaths": [(2, 0.37), (4, 1.0)].map { frame, progress in
            [IconLayer.base, .accent, .wash].map { layer in
                InkIconShape(glyph: glyph, direction: .doodle, layer: layer, frame: frame, progress: progress).path(in: CGRect(x: 0, y: 0, width: 24, height: 24)).polygons.map { $0.map(point) }
            }
        }]
}
FileHandle.standardOutput.write(try JSONSerialization.data(withJSONObject: data, options: [.sortedKeys]))
"""
with tempfile.TemporaryDirectory(prefix="zoen-ink-icons-") as directory:
    source = Path(directory) / "icons.swift"
    executable = Path(directory) / "icons"
    source.write_text("import Foundation\nimport CoreGraphics\n" + path_support + rng + geometry + enum + seed + art + shape + motion + export)
    subprocess.run(["swiftc", "-O", str(source), "-o", str(executable)], check=True)
    data = json.loads(subprocess.run([str(executable)], check=True, capture_output=True).stdout)

def number(value):
    return repr(float(value))

def point(value):
    return f"InkPoint({number(value[0])}, {number(value[1])})"

def marks(values):
    items = []
    for m in values:
        p = ", ".join(point(x) for x in m["points"])
        items.append(f"InkMark(listOf({p}), {str(m['closed']).lower()}, {str(m['smooth']).lower()}, {number(m['weight'])}, {str(m['overshoot']).lower()})")
    return "listOf(" + ",\n                ".join(items) + ")"

def blots(values):
    return "listOf(" + ", ".join(f"InkBlot({point(p)}, {number(p[2])})" for p in values) + ")"

lines = ["package xyz.tironi.zoen.ui.ink", "", "// Generated by scripts/export-android-ink-icons.py from the original Swift art."]
for path in (icons, glyphs):
    lines.append(f"// {path.relative_to(root)} SHA-256 {hashlib.sha256(path.read_bytes()).hexdigest()}")
lines += ["internal enum class ZoenGlyph { " + ", ".join(x["name"].capitalize() for x in data) + " }", "", "internal object ZoenIconArt {", "    val all = mapOf("]
for item in data:
    lines += [f"        ZoenGlyph.{item['name'].capitalize()} to InkIconArt(", f"            seed = {item['seed']}uL,", f"            base = {marks(item['base'])},", f"            accent = {marks(item['accent'])},", f"            blots = {blots(item['blots'])},", f"            accentBlots = {blots(item['accentBlots'])},", f"            wash = {marks(item['wash'])},", f"            pivot = {point(item['pivot'])},", "            beats = listOf(" + ", ".join("IconMotion(" + ", ".join(number(x) for x in beat) + ")" for beat in item["beats"]) + "),", "        ),"]
lines += ["    )", "}", ""]
target = root / "android/app/src/main/java/xyz/tironi/zoen/ui/ink/GeneratedInkIcons.kt"
target.write_text("\n".join(lines))
reference = root / "android/app/src/test/resources/ink-icons-swift-reference.json.gz"
reference.parent.mkdir(parents=True, exist_ok=True)
reference.write_bytes(gzip.compress(json.dumps({"icons": data, "sources": {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest() for p in (icons, glyphs, hand)}}, separators=(",", ":"), sort_keys=True).encode(), mtime=0))
print(f"{len(data)} original vector icons and their four motion beats; {target.relative_to(root)}")
